version: '3.8'

services:
  api:
    container_name: web-blog-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - web-blog-network

  db:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root_password  # Replace with your MySQL root password
      - MYSQL_DATABASE=dotnet-boilerplate  # Replace with your MySQL database name
      - MYSQL_USER=mysql_user             # Replace with your MySQL username
      - MYSQL_PASSWORD=mysql_password     # Replace with your MySQL password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - web-blog-network

volumes:
  db-data:

networks:
  web-blog-network:
