version: '3.8'

services:
  api:
    container_name: web-blog-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped
    depends_on:
      - db
      - redis
    networks:
      - web-blog-network

  db:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456Aa  # Replace with your MySQL root password
      - MYSQL_DATABASE=web-blog-db  # Replace with your MySQL database name
      - MYSQL_USER=devs             # Replace with your MySQL username
      - MYSQL_PASSWORD=123456Aa     # Replace with your MySQL password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - web-blog-network

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - web-blog-network

volumes:
  db-data:

networks:
  web-blog-network:
